// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKPxUUofmjbB9IthA7_SWizNvWMVq2Hv0',
    appId: '1:624313489056:web:ef322fcc09838951355bc5',
    messagingSenderId: '624313489056',
    projectId: 'socialapp01-37067',
    authDomain: 'socialapp01-37067.firebaseapp.com',
    storageBucket: 'socialapp01-37067.appspot.com',
    measurementId: 'G-8BJ9XQ5NNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXcD_QLS-2pbgzw7JlBb0XeaZTh8qlRN4',
    appId: '1:701534474497:android:7af9894fab3797f8584b00',
    messagingSenderId: '701534474497',
    projectId: 'socialapp-d729f',
    storageBucket: 'socialapp-d729f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgflqkRKmrfj2h1eiRiBVTldLyQDDuCJ4',
    appId: '1:624313489056:ios:8088c48957ab3d7b355bc5',
    messagingSenderId: '624313489056',
    projectId: 'socialapp01-37067',
    storageBucket: 'socialapp01-37067.appspot.com',
    iosBundleId: 'com.example.socialApp05',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgflqkRKmrfj2h1eiRiBVTldLyQDDuCJ4',
    appId: '1:624313489056:ios:8088c48957ab3d7b355bc5',
    messagingSenderId: '624313489056',
    projectId: 'socialapp01-37067',
    storageBucket: 'socialapp01-37067.appspot.com',
    iosBundleId: 'com.example.socialApp05',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKPxUUofmjbB9IthA7_SWizNvWMVq2Hv0',
    appId: '1:624313489056:web:b70a456625406e5d355bc5',
    messagingSenderId: '624313489056',
    projectId: 'socialapp01-37067',
    authDomain: 'socialapp01-37067.firebaseapp.com',
    storageBucket: 'socialapp01-37067.appspot.com',
    measurementId: 'G-8D8HEVRC7H',
  );
}